### PR TITLE
Malformated jwt is handled

### PR DESCRIPTION
**Pull request by andmagom**
#50 JWT Error

Hello, the problem with authentication was that the front end is sending an authorization header with "null" value, so the server can't parse this token JWT and an exception is throwed.

Front-end sets a undefined value
image

Server gets a "null" value
image

This PR fix that problem,
Have a nice day

### CODE REVIEW

**Comment by rvema** [comment]
@andmagom Please sign the [CLA](https://cla-assistant.io/Hygieia/api?pullRequest=99) so that we can accept the change

**Comment by rvema** [comment]
also please ensure that the checks pass, most likely the issue is with import statements

**Comment by andmagom** [comment]
@rvema Thanks you, I have fixed the issue with import statements. I have signed the CLA but it is not reflexed at the moment. Idon't know why is this happening

**Comment by andmagom** [comment]
CLA signed !

**Comment by andmagom** [comment]
Any suggestion ? @rvema

**Pull request merged**
