### PR TITLE
SAST refactor

### PR DESCRIPTION
**Pull request by tatlax3636**
* refactored the code used to get code-quality results for the UI SAST widget
* moved the endpoint to a new controller "widgetController" since it is specifically for the UI

### CODE REVIEW

**Comment by nameisaravind** [comment]
@tatlax3636 can this api be part of existing controller and not marked like "ui only"? you may use the endpoint - /v2/quality/security-analysis

**Comment by tatlax3636** [comment]
> @tatlax3636 can this api be part of existing controller and not marked like "ui only"? you may use the endpoint - /v2/quality/security-analysis

@nameisaravind Ragha asked for it to be moved to its own controller

**Review by rvema — APPROVED** [review]
lgtm

**Review by rvema — APPROVED** [review]
lgtm

**Review by rvema — CHANGES_REQUESTED** [review]
please increment the version in pom.xml to `3.4.18-SNAPSHOT`

**Review by rvema — APPROVED** [review]
lgtm

**Pull request merged**
